name: DefectDojo Scan Upload (Insecure SSL)

on:
  push:
    branches:
      - '**'   # ✅ Trigger on all branches
  workflow_dispatch:  # ✅ Manual trigger

jobs:
  defectdojo-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code repository
        uses: actions/checkout@v2

      # 2. Validate Secrets (Fail early if missing)
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DEFECTDOJO_URL }}" ]; then
            echo "❌ DEFECTDOJO_URL is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
            echo "❌ DEFECTDOJO_TOKEN is missing!"
            exit 1
          fi
          echo "✅ Secrets present."

      # 3. Test API Connectivity (insecure SSL)
      - name: Test API Connectivity (Insecure SSL)
        run: |
          API_URL="${{ secrets.DEFECTDOJO_URL }}/api/v2/system_settings/"
          echo "Testing API URL (insecure SSL): $API_URL"
          curl -vk $API_URL \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json"

      # 4. Create Reports Folder
      - name: Create reports directory
        run: mkdir -p reports

      # 5. Run Trivy Scan (official action)
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: json
          output: reports/trivy-scan-report.json

      # 6. Upload Report to DefectDojo (manual curl with -k)
      - name: Upload Scan Report to DefectDojo (Insecure SSL)
        run: |
          echo "Uploading scan report to DefectDojo..."
          curl -vk -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trivy Scan" \
            -F "engagement=1" \
            -F "file=@reports/trivy-scan-report.json"

      # 7. Confirm Completion
      - name: Show Confirmation
        run: echo "✅ Scan uploaded to DefectDojo (SSL verification skipped)."
