name: DefectDojo Scan Upload

on:
  push:
    branches:
      - '**'        # ✅ Trigger on all branches
  workflow_dispatch:  # ✅ Allow manual runs from Actions UI

jobs:
  defectdojo-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Validate Required Secrets
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DEFECTDOJO_URL }}" ]; then
            echo "❌ DEFECTDOJO_URL is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
            echo "❌ DEFECTDOJO_TOKEN is missing!"
            exit 1
          fi
          echo "✅ Secrets validated."

      # 3. Test DefectDojo API Connectivity (SSL verified)
      - name: Test DefectDojo API
        run: |
          echo "Testing API endpoint: ${{ secrets.DEFECTDOJO_URL }}/api/v2/system_settings/"
          curl -s -o /dev/null -w "%{http_code}\n" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/system_settings/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json"

      # 4. Create Reports Folder
      - name: Create reports directory
        run: mkdir -p reports

      # 5. Run Trivy Scan (official action - vulnerabilities only)
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: vuln          # ✅ Only scan for vulnerabilities (no secrets)
          format: json
          output: reports/trivy-scan-report.json

      # 6. Fail if Critical Vulnerabilities are Found
      #- name: Fail on Critical Vulnerabilities
       # run: |
        #  echo "Checking for Critical vulnerabilities..."
         # trivy fs . --scanners vuln --severity CRITICAL --exit-code 1 || echo "No critical vulns or failing step skipped."

      # 7. Reimport Report to DefectDojo (deduplicated)
      - name: Reimport Scan Report to DefectDojo
        run: |
          echo "Reimporting scan report to DefectDojo (deduplicating)..."
          curl -s -o response.json -w "%{http_code}\n" -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trivy Scan" \
            -F "engagement=1" \
            -F "file=@reports/trivy-scan-report.json" \
            -F "test_title=Automated Trivy Scan" \
            -F "deduplication_on_engagement=true"

      # 8. Show API Response
      - name: Show API Response
        run: |
          echo "✅ DefectDojo API response:"
          cat response.json
