name: DefectDojo Scan Upload (SSL Host Mapping)

on:
  push:
    branches:
      - '**'   # ✅ Trigger on all branches
  workflow_dispatch:  # ✅ Manual trigger option

jobs:
  defectdojo-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code repository
        uses: actions/checkout@v2

      # 2. Validate Secrets (Fail early if missing)
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DEFECTDOJO_URL }}" ]; then
            echo "❌ DEFECTDOJO_URL is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
            echo "❌ DEFECTDOJO_TOKEN is missing!"
            exit 1
          fi
          echo "✅ Secrets present."

      # 3. Map hostname to IP (SSL workaround while DNS propagates)
      - name: Map hostname to IP for SSL
        run: |
          echo "16.171.57.1 thedisclosure.show" | sudo tee -a /etc/hosts
          echo "✅ Mapped thedisclosure.show to 16.171.57.1"

      # 4. Test DefectDojo API Connectivity
      - name: Test API Connectivity (SSL valid now)
        run: |
          API_URL="${{ secrets.DEFECTDOJO_URL }}/api/v2/system_settings/"
          echo "Testing API URL: $API_URL"
          curl -v $API_URL \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json"

      # 5. Create Reports Folder
      - name: Create reports directory
        run: mkdir -p reports

      # 6. Run Trivy Scan (official action)
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: json
          output: reports/trivy-scan-report.json

      # 7. Upload Report to DefectDojo (no -k needed)
      - name: Upload Scan Report to DefectDojo
        run: |
          echo "Uploading scan report to DefectDojo..."
          curl -v -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trivy Scan" \
            -F "engagement=1" \
            -F "file=@reports/trivy-scan-report.json"

      # 8. Confirm Completion
      - name: Show Confirmation
        run: echo "✅ Scan uploaded to DefectDojo successfully."
