name: DefectDojo Scan Upload (IP-Based)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  defectdojo-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Test API Connectivity (IP)
        run: |
          curl -vk https://${{ secrets.DEFECTDOJO_IP }}/api/v2/system_settings/ \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
          -H "accept: application/json" || exit 1

      - name: Run Trivy Scan
        run: |
          trivy fs. -f json -o reports/trivy-scan-report.json

      - name: Publish report to DefectDojo (IP)
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_url: https://${{ secrets.DEFECTDOJO_IP }}
          file: reports/trivy-scan-report.json
          scan_type: Trivy Scan
          engagement: 1
          defectdojo_endpoint: /api/v2/import-scan/

      - name: Show API response
        run: |
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'

