name: TruffleHog - Deduplicated Reimport

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  defectdojo-reimport:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Validate Secrets
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DEFECTDOJO_URL }}" ] || [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
            echo "❌ Missing required secrets"
            exit 1
          fi
          echo "✅ Secrets validated."

      # 3. Create Reports Folder
      - name: Create reports directory
        run: mkdir -p reports

      # 4. Run TruffleHog Git Scan
      - name: Run TruffleHog Git Scan
        run: |
          docker run --rm -v $PWD:/pwd ghcr.io/trufflesecurity/trufflehog:latest git file:///pwd --json > reports/trufflehog-scan-report.json || true

      # 5. Check for Findings
      - name: Check Findings
        id: check-findings
        run: |
          if ! grep -q '"DetectorName"' reports/trufflehog-scan-report.json; then
            echo "skip_upload=true" >> $GITHUB_OUTPUT
          fi

      # 6. Fetch Product & Engagement IDs
      - name: Fetch Product & Engagement IDs
        id: ids
        run: |
          PRODUCT_NAME="TruffleHog Scan"
          ENGAGEMENT_NAME="TruffleHog CI/CD Scans"

          PRODUCT_ID=$(curl -sk "${{ secrets.DEFECTDOJO_URL }}/api/v2/products/?name=${PRODUCT_NAME// /%20}" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" | jq '.results[0].id')

          ENGAGEMENT_ID=$(curl -sk "${{ secrets.DEFECTDOJO_URL }}/api/v2/engagements/?name=${ENGAGEMENT_NAME// /%20}&product=$PRODUCT_ID" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" | jq '.results[0].id')

          if [ "$PRODUCT_ID" = "null" ] || [ -z "$PRODUCT_ID" ]; then
            echo "❌ Product not found in DefectDojo"
            exit 1
          fi
          if [ "$ENGAGEMENT_ID" = "null" ] || [ -z "$ENGAGEMENT_ID" ]; then
            echo "❌ Engagement not found for product ID $PRODUCT_ID"
            exit 1
          fi

          echo "product_id=$PRODUCT_ID" >> $GITHUB_OUTPUT
          echo "engagement_id=$ENGAGEMENT_ID" >> $GITHUB_OUTPUT

      # 7. Reimport Scan with Deduplication
      - name: Reimport Scan Report
        if: steps.check-findings.outputs.skip_upload != 'true'
        run: |
          echo "Reimporting TruffleHog scan..."
          curl -s -o response.json -w "%{http_code}\n" -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trufflehog Scan" \
            -F "product_name=TruffleHog Scan" \             # ✅ Explicitly included
            -F "product_id=${{ steps.ids.outputs.product_id }}" \  # ✅ Also included ID
            -F "engagement=${{ steps.ids.outputs.engagement_id }}" \
            -F "file=@reports/trufflehog-scan-report.json" \
            -F "test_title=Automated TruffleHog Reimport" \
            -F "deduplication_on_engagement=true"

      # 8. Show API Response
      - name: Show API Response
        if: steps.check-findings.outputs.skip_upload != 'true'
        run: cat response.json
