name: TruffleHog - Deduplicated Reimport

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  defectdojo-reimport:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Validate Secrets
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DEFECTDOJO_URL }}" ] || [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
            echo "❌ Missing required secrets"
            exit 1
          fi

      # 3. Create Reports Folder
      - name: Create reports directory
        run: mkdir -p reports

      # 4. Run TruffleHog Scan
      - name: Run TruffleHog Git Scan
        run: |
          docker run --rm -v $PWD:/pwd ghcr.io/trufflesecurity/trufflehog:latest git file:///pwd --json > reports/trufflehog-scan-report.json || true

      # 5. Check for Findings
      - name: Check Findings
        id: check-findings
        run: |
          if ! grep -q '"DetectorName"' reports/trufflehog-scan-report.json; then
            echo "skip_upload=true" >> $GITHUB_OUTPUT
          fi

      # 6. Reimport Scan Report Using Names
      - name: Reimport Scan Report
        if: steps.check-findings.outputs.skip_upload != 'true'
        run: |
          echo "Reimporting TruffleHog scan using engagement_name..."
          HTTP_CODE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trufflehog Scan" \
            -F "product_name=TruffleHog Scan" \
            -F "engagement_name=TruffleHog CI/CD Scans" \
            -F "file=@reports/trufflehog-scan-report.json" \
            -F "test_title=Automated TruffleHog Reimport" \
            -F "deduplication_on_engagement=true")

          echo "HTTP Response Code: $HTTP_CODE"
          cat response.json
          if [ "$HTTP_CODE" -ne 200 ] && [ "$HTTP_CODE" -ne 201 ]; then
            echo "❌ Reimport failed with HTTP $HTTP_CODE"
            exit 1
          fi
