name: Trufflehog Scan and Upload

on:
  push:
    branches: '**'
  workflow_dispatch: 

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
     # ✅ Run TruffleHog Git scan (full commit history)
      - name: Run TruffleHog Git Scan
        run: |
          echo "Running TruffleHog Git scan (full history)..."
          docker run --rm -v $PWD:/pwd ghcr.io/trufflesecurity/trufflehog:latest git file:///pwd --json > reports/trufflehog-report.json || true

      - name: Upload to DefectDojo
        id: import-trufflehog
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
          file: reports/trufflehog-scan-report.json
          scan_type: Trufflehog Scan
          engagement: 1

      - name: Show API Response
        run: |
          printf '%s\n' '${{ steps.import-trufflehog.outputs.response }}'
