name: T2

on:
  push:
    branches: '**'
  workflow_dispatch: 

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ✅ Ensure reports folder exists
      - name: Create Reports Folder
        run: mkdir -p reports
      
      # ✅ Run TruffleHog Git scan (full commit history)
      - name: Run TruffleHog Git Scan
        run: |
          echo "Running TruffleHog Git scan (full history)..."
          docker run --rm -v $PWD:/pwd ghcr.io/trufflesecurity/trufflehog:latest git file:///pwd --json > reports/trufflehog-scan-report.json || true

      - name: Debug TruffleHog Output
        run: |
          echo "Checking TruffleHog report contents..."
          cat reports/trufflehog-scan-report.json || echo "No report found"

      # ✅ Upload to DefectDojo
      - name: Reimport Scan Report to DefectDojo
        run: |
          echo "Reimporting scan report to DefectDojo (deduplicating)..."
          curl -s -o response.json -w "%{http_code}\n" -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -H "accept: application/json" \
            -F "scan_type=Trufflehog3 Scan" \
            -F "engagement=10" \
            -F "file=@reports/trufflehog-scan-report.json" \
            -F "test_title=Automated Trufflehog Scan" \
            -F "deduplication_on_engagement=true"

      # ✅ Show API Response
      - name: Show API Response
        run: |
          printf '%s\n' '${{ steps.import-trufflehog.outputs.response }}'
